### ISSUE TITLE
FGSM Targetted

### ISSUE THREAD

**Issue by AsimJalwana** [rodgzilla/machine_learning_adversarial_examples#2]
Hi, 

In your Adversarial examples - targeted FGSM.ipynb, there is some problem. It does not becomes the target class. Have you also noticed this?

**Comment by rodgzilla** [comment]
Hi,

The code in the targeted FGSM notebook is the same as the one in the FGSM one. I meant to work on the targeted version of the attack but never got around to it.

If you want to read good attack implementations, you should to to [CleverHans](https://github.com/tensorflow/cleverhans).

**Comment by AsimJalwana** [comment]
Hi,

Thank you for the quick reply, I will definitely check CleverHans. I did like the easy to understand code of yours.
